server:
  port: 8086
  servlet:
    context-path: /api/blog-service

spring:
  datasource:
    name: helloblog
    url: jdbc:mysql://127.0.0.1:3306/helloblog?useSSL=false&characterEncoding=utf8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB  #设置支持的单个上传文件大小
      max-request-size: 6MB  #设置最大的请求文件大小，设置总体大小的请求
      file-size-threshold: 512KB #当上传文件达到指定配置量的时候，会将文件内容写入到磁盘
      location: /   #设置上传文件的临时目录